### ISSUE TITLE
1.2.0 OTA bricked RATGDO

### ISSUE THREAD

**Issue by infamous-pattern** [ratgdo/homekit-ratgdo#151] opened 2024-04-04 12:37 UTC
Guys:

I'm not sure what happend, but this morning I installed the 1.2.0 update via the web interface and my RATGDO bricked. It went through the update process without issue and then rebooted but never came back up. I waited 15 minutes, but no luck. So I removed it, attached it to my PC via USB, and attempted to re-flash it. The first attempt failed, so I rebooted my PC and gave it another go. The second time worked and now its functioning normally again. I just wanted to make y'all aware in case this happens to anyone else. 

Thanks.

**Comment by Damien514** [comment] 2024-04-04 12:48
Same for me, bricked.
I am going to plug my laptop to it and restore...

**Comment by jgstroud** [comment] 2024-04-04 13:00
Wow, sorry about that.  I upgraded both of mine to the release build as soon as it was ready to make sure there were no issues.  2 people having the same issue doesn't seem like a fluke.  Were you both upgrading from 1.1.0?

**Comment by Damien514** [comment] 2024-04-04 13:15
I didn't recovered, but will do. Any clue on how to get the logs for you?

**Comment by donavanbecker** [comment] 2024-04-04 13:25
Sane thing happened to me, but re-flashed (didn't erase device) once and everything was as it was before the update.

**Comment by jgstroud** [comment] 2024-04-04 13:26
If you use the web flash utility to recover it, that also has the ability to connect to the serial console.  From there you can hit the reboot button, wait for it to boot and then download the logs.  If you can't get it, no problem.

**Comment by jgstroud** [comment] 2024-04-04 13:26
Ugh.... 3 people now

I wonder if this is a v1.1.0 or a v1.2.0 problem.

**Comment by eric-ooi** [comment] 2024-04-04 13:33
Not bricked, but it wouldn't update from 1.1.0 to 1.2.0 when using the "Update from GitHub" option.  Tried twice and it'd just reboot back to 1.1.0.  Eventually, I downloaded the firmware manually and used the "Update from local file" option and it rebooted into 1.2.0 just fine.

**Comment by infamous-pattern** [comment] 2024-04-04 13:38
No worries; stuff happens. Yes, I was on 1.1.0 when I ran the Update from GitHub update this morning. Mine woulnd't come back at all so I had to do a complete erase and re-flash.

**Comment by jgstroud** [comment] 2024-04-04 13:52
I just flashed the official v1.1.0 and then upgraded to v1.2.0 and no issues.  Again clearly there is an issue, but I gotta figure out how to reproduce.

**Comment by jgstroud** [comment] 2024-04-04 13:53
At least they are all coming back up after doing the USB upgrade.

**Comment by Damien514** [comment] 2024-04-04 14:39
Empty logs, I think that rebooting the device cleared them all. I tries twice to flash. Success, but it was not working. I suspected that there was a network issue. I think the issue was more a Wifi password "forgotten". I re-entered it while connected over USB after my third flash, and now it's working as expected.

**Comment by jgstroud** [comment] 2024-04-04 14:41
I suspect the OTA just completely bombed and left the device unbeatable.  Thanks.  Sorry for the trouble.  Glad it's working now.  I'll keep trying to reproduce the issue.

**Comment by jgstroud** [comment] 2024-04-04 14:43
Mentioning @dkerr64.  Maybe he has some ideas.

**Comment by dkerr64** [comment] 2024-04-04 15:58
Like @jgstroud I have successfully updated my ratgdo's without issue, I just tried again from GitHub as previously I had used local file.

Upgrading from GitHub or from a local file should make no difference... In both cases the upgrade goes through the browser, so where the bin file comes from is different, but the subsequent transfer from browser to ratgdo is the same for both.

One thing we don't do that perhaps we should is have a SHA-1 or CRC for the bin file, and in the browser check that the file downloaded without error.  Now-a-days I think transfer errors at the app layer would be extremely rare, the underlying TCP stack should re-request any bad packets.  But it is a gap.

I do not know how we could capture any logs of the update / reboot process.  We are looking at how we can persistently save a log in the ratgdo, but right now the design point is to save only if a crash occurs, not continuously save to flash for fear of wearing it out (how durable is the ESP8266 flash supposed to be, is this a real concern?).

David

**Comment by dkerr64** [comment] 2024-04-04 16:05
@jgstroud You may be onto something here... we should certainly stop all running tickers during the upgrade process.  There is no need to continue Server-Sent-Event notifications to the browser during upgrade.  I'll look into that.

**Comment by cefoster0** [comment] 2024-04-05 16:22
So do we think we can update 1.1 to 1.2.1 via file and it will be ok? or does it need to be USB?

**Comment by dkerr64** [comment] 2024-04-05 16:28
> So do we think we can update 1.1 to 1.2.1 via file and it will be ok? or does it need to be USB?

For most people updating from either GitHub or local file is working fine.  USB is only necessary to recover if OTA update fails.  We suspect that OTA may be failing if you have poor internet or WiFi connection and we have changes queued to to be more tolerant of that and suspend any other network and GDO activity while update is in progress.

If your internet connection is slow then you might want to download the bin file first then use it to upgrade rather than direct from GitHub... but we have no good reason as to why there would be any difference.

**Comment by infamous-pattern** [comment] 2024-04-05 16:49
> So do we think we can update 1.1 to 1.2.1 via file and it will be ok? or does it need to be USB?

Yesterday, ine bricked upgradinbg to 1.2 OTA, but I just upgrade to 1.2.1 OTA without isses.

**Comment by TLee1964** [comment] 2024-04-10 00:58
OTA also fails from v0.11.0. Looking for my USB cable...

**Comment by jgstroud** [comment] 2024-04-10 15:03
Thanks for the feedback.  Anything release prior to release v1.0.0 is a roll of the dice because we had so many problems.  I have yet to be able to reproduce this issue, but we have implemented several safeguards to ensure reliability of the OTA process going forward.

**Comment by Cristov9000** [comment] 2024-04-11 18:11
I just updated from 1.1 to 1.2.1 and it bricked the RATGDO.  I have 4 other RATGDO on 1.1, is there any way to avoid this when upgrading those?

**Comment by dkerr64** [comment] 2024-04-11 22:40
> I just updated from 1.1 to 1.2.1 and it bricked the RATGDO. I have 4 other RATGDO on 1.1, is there any way to avoid this when upgrading those?

Did you update from GitHub or from a local copy of the firmware.bin file?

**Comment by paint697** [comment] 2024-04-12 02:30
My 1.1.0 to 1.2.1 OTA upgrade bricked my unit. My AP is co-located with the unit in the garage and I have locked my ratgdo's MAC to only use that AP.  How do I recover?

**Comment by dkerr64** [comment] 2024-04-12 02:52
> My 1.1.0 to 1.2.1 OTA upgrade bricked my unit. My AP is co-located with the unit in the garage and I have locked my ratgdo's MAC to only use that AP. How do I recover?

You will need to erase/flash using USB cable from computer/laptop like your initial setup.

Did you update from GitHub or local file?  We are working on adding checksum to ensure integrity of uploaded files which will hopefully prevent this error.

**Comment by paint697** [comment] 2024-04-12 05:29
I updated from GitHub. I was able to erase/flash over USB and it’s working
now. Thanks for responding.


Regards,

Jeff

**Comment by dangerusty** [comment] 2024-04-12 14:37
I've connected mine to USB, reset erased and installed the latest firmware, but the WiFi does not connect: "Unable to connect".

**Comment by paint697** [comment] 2024-04-12 14:43
I had a similar issue with mine. I had previously "locked" mine to one of my APs. I had to temporarily remove that lock and then I could get the ratgdo back on my WiFi and I could again lock it to my AP.

**Comment by dangerusty** [comment] 2024-04-12 14:50
> I had a similar issue with mine. I had previously "locked" mine to one of my APs. I had to temporarily remove that lock and then I could get the ratgdo back on my WiFi and I could again lock it to my AP.

Ah, thank you! I had to dig deep on the Unifi console to find the offline device from a while ago and disable the lock. It works now.

**Comment by dkerr64** [comment] 2024-04-13 02:10
Thanks for all the reports.  I have firmware update integrity checksum code in test which will hopefully prevent this in future (after next release of course).

**Comment by Damien514** [comment] 2024-04-13 02:21
Since this update, my RATGDO keep disconnecting after 12-18h. Not connecting to Wifi, even after switching it OFF/ON. I have to re-flash the 1.2.1 update to make it run again (meaning move the cars, take a ladder, plug the Mac to the RATGDO...). Thing is I can't export the logs, they are empty when I re-flash.
It has been running solid for weeks on the previous version, so it's really weird.

**Comment by Cristov9000** [comment] 2024-04-13 03:05
> > I just updated from 1.1 to 1.2.1 and it bricked the RATGDO. I have 4 other RATGDO on 1.1, is there any way to avoid this when upgrading those?
> 
> Did you update from GitHub or from a local copy of the firmware.bin file?

I updated via github.  Is it possible to avoid plugging into the other 4 units to upgrade? or do I just need to get it over with?

**Comment by jgstroud** [comment] 2024-04-15 02:57
There seems to be an issue with fetching the binary from GitHub.  Just download it first and use the local file update method.  As @dkerr64 mentioned, there is a fix coming in the next release to address this issue.

**Comment by cefoster0** [comment] 2024-04-15 14:03
Should I try the local upload with 1.2.1 or wait for some of the other commits in the next release?

**Comment by jgstroud** [comment] 2024-04-15 14:07
It's entirely up to you.  The next release should be coming probably end of the week or early next week.

**Comment by jgstroud** [comment] 2024-04-30 20:02
Hopefully fixed in #145

**Closed as completed by jgstroud** 2024-04-30 20:02 UTC

**Comment by cefoster0** [comment] 2024-05-01 13:10
> Hopefully fixed in #145

Updated from 1.2.1 to 1.3.2 successfully via local file. Great job fixing this!
