### ISSUE TITLE
HomeKit No Response

### ISSUE THREAD

**Issue by SausCode** [ratgdo/homekit-ratgdo#30] opened 2023-12-13 00:22 UTC
Hi!

Thanks for creating this. I installed successfully, and was able to open and close the garage door a few times using the Home app.

It seems like after an hour or so, HomeKit reports "No response". It seems like I can occasionally ping the device, though not reliably. The wifi strength at the location is good, I've got an AP that it's connected to very close.

Are there any logs or anything I can do to help investigate?

Also it appears the discord link might be expired.

**Comment by donavanbecker** [comment] 2023-12-13 00:23
Try rebooting from the web server

**Comment by SausCode** [comment] 2023-12-13 00:25
@donavanbecker That's true, and restarting the ESP works fine as well, I'm just trying to see if I can provide any useful data to fix this more reliably.

**Comment by thenewwazoo** [comment] 2023-12-13 02:07
This is, as its core, a dupe of #24, so I'm going to close it and put some thoughts there. "How do I see the serial logs from before something went wrong?" is not a problem I have an solid answer to yet.

**Closed by thenewwazoo** 2023-12-13 02:07 UTC
